### ISSUE TITLE
Keyboard Shortcuts for Safari version?

### ISSUE THREAD

**Issue by sjl** [robnyman/HTML-Validator#1]
It would be nice if there were keyboard shortcuts for the Safari version of the plugin.  I tried the ones listed on the linked page but they don't work.

**Comment by robnyman** [comment]
The Safari version should mostly be seen as a testing ground - besides, one of the problems with keyboard shortcuts are that they will only work when the web content area has focus, otherwise not.

It might be added in the future, and if you're keen to experiment, feel free to fork the project and try it out.
